### ISSUE TITLE
sorting track/waypoints/routes

### ISSUE THREAD

**Issue by pfps** [viking-gps/viking#105]
I have several GPS files with between 15 and 20 tracks.  When I load the file into Viking the tracks show up in the layer pane in what appears to be a random order.   This makes it hard to find a particular track.  Is there any way to tell Viking to order the tracks by name?  If not, please consider adding some way to order tracks.

**Comment by rnorris** [comment]
Viking by default should display the tracks in the order they are stored in the GPX file.

You can change the sort order by right clicking on the specific layer in the left hand pane and select:
Properties-->Tracks Advanced-->Track Sort Order
Options include Name, Date and 'Number' (which uses the explicit GPX Number property).

There is an equivalent option for Waypoints, under the Waypoints tab in the same layer Properties. 
Waypoint Sort Order is at the bottom.

You can change the default behaviour by changing these values via the File Menu:
Edit-->Layer Defaults->TrackWaypoint...

So that will apply to any newly created/loaded TrackWaypoint layer from GPS files.

**Comment by pfps** [comment]
Thanks, the sorting works.
