### ISSUE TITLE
Unable to save tile

### ISSUE THREAD

**Issue by apinunt** [viking-gps/viking#109]
Just upgraded to Ubuntu 20.10 Mate,  and installed Viking 1.8
I selected Open Topo maps and the tiles download, but the bottom of the screen presents a message 
OpenTopoMap: Unable to save tile
The tiles appear to be saved, but looking in the .viking-maps directory the are being saved in a directory 
named Unknown.
If I rename the directory OpenTopoMap I no longer get the message, but a new Unknown directory is created
and that is where the files continue to be stored.

**Comment by rnorris** [comment]
I think this is the same as Issue #92 (fixed in the latest source).
    
As a workaround you can add appropriate "name" line into the system installed maps.xml file. Typically this is located in /usr/share/viking:

    <property name="name">OpenTopoMap</property>

Alternatively setting the Map Layer property Cache Layout: to "Viking" should work as well.

HTH.

**Comment by apinunt** [comment]
Wouldn't it be better to move a copy of maps.xml to the users home when viking is initially opened?
Then after a fresh install you don't have to modify config files in root, plus multiple users could make changes they need without needing root access.
I did make the change in maps,xml as you suggested, and that resolved the problem.
I do have 2 questions still.
1. Will vector maps ever become supported in viking?
2. Can I put a copy of maps.xml in my home directory somewhere that will take precedence over the one in the system?

Thank you.

**Comment by rnorris** [comment]
1. For 'ever' is a long time. As an Open Source project it's up to contributors to support it. I personally don't have the need for vectors maps, nor the time to implement it - although it would of course be nice. It would not be an easy thing to add.

2. Yes you can. Viking will read from both the system and home locations. Values in the home will supercede those previously read. Hopefully this is covered in the manual + [wiki](https://sourceforge.net/p/viking/wikiallura/Maps/). The intention is more that those in your home location supplement the system defined one so that you can add additional map resources.
The location for the file is:

    ~/.viking/maps.xml
