### ISSUE TITLE
Large number of downloads

### ISSUE THREAD

**Issue by yourealwaysbe** [viking-gps/viking#112]
When moving around the map, a large number of downloads are generated -- it is quite easy to rack up several thousand. Here is a video:

https://www.dropbox.com/s/qaftbqb9auh3mba/downloads.mp4?dl=0

My impression is that most of these downloads don't translate to real downloads. Instead, multiple threads get started with the job of downloading overlapping tiles, so most don't do the download when they find the tile already exists. Here is [a debug log]](https://github.com/viking-gps/viking/files/5863324/downloads.log) of a run similar to the above. It looks like 362 threads for about 7000 downloads (according to the GUI counter), but only 43 actual tiles.

I mentioned this is #111 but i think it's a separate issue. I will look into it more later.

**Comment by rnorris** [comment]
The checks to see if it really needs to create new requests (or not - since an outstanding request on the same tile is in progress) are performed inside the threads; so in itself that recent change should not effect the numbers reported in the Jobs part of the GUI.

I suppose that part that creates the number of tiles to be fetched in the thread can be improved to:
 Not count items if they already in the request queue.
This would also then avoid creating a new thread of otherwise already requested tiles.

Be aware that in the GTK3-WIP branch there is currently 1/2 second delay artificially inserted for my testing purposes "g_usleep(G_USEC_PER_SEC/2)"; which shouldn't really be there - (there is no intention to put that in the mainline). 
Remove that and see how things behave.

**Comment by yourealwaysbe** [comment]
> Be aware that in the GTK3-WIP branch there is currently 1/2 second delay artificially inserted in vikmapslayer.c for my testing purposes "g_usleep(G_USEC_PER_SEC/2)"; which shouldn't really be there

Aha! Thanks -- that makes a big difference. The numbers stay within the realms i'm used to seeing with Viking once it is commented out.

I guess ideally the fewer threads created the better -- shall i leave this open or call it closed and thread optimisation can be left for another day?

**Comment by rnorris** [comment]
I'll improve the reported numbers under this issue; the artificial delay represents a slow network / slow to respond server.
And it shouldn't be much effort to resolve.
