### ISSUE TITLE
Delay before right-click menu pops up

### ISSUE THREAD

**Issue by roooots** [viking-gps/viking#113]
Hi,

I've found this strange already for a while, but when I right-click on a track point, map etc. in the map window to get the context menu, it takes what feels like a second or so for the menu to pop up. On the other hand, there is no such delay in the side pane. Is there a specific purpose for that delay, is it a bug and/or can it be removed without much hassle?

Cheers,
r.

**Comment by rnorris** [comment]
In order to differentiate between single clicks and double clicks, Viking waits for the GTK double click time plus 50ms before deciding it was only a single click.
This is currently 'by design' - due to #87 - a double right click on the viewport (when using the Select Tool) zooms out. This is to integrate the double click behaviours of the pan tool mode in the default select tool mode.

NB This should only be for tracks/waypoints. For a Map Layer, you'd need to use the Map Download Tool - and this does not contain any such double click waiting code.

The select tool could be modified in a couple of different ways:
- An configurable option to not use double click zooms - thus it would avoid any waits and show the menus immediately.
- See if the right click is over the selected item and if so immediately bring up the menu. If elsewhere then it would function as now, in that it would wait to see if it a double click.

**Comment by roooots** [comment]
I see...I never used the double click zoom before, because I find the mouse wheel zooming much more handy. So I did not really consider any clicking differentiation. As for the solution I guess option #1 would be the easiest to implement. Would you give me a quick pointer where the click evaluation is implemented in the code so I could toy around a bit if find the time?

Thanks.
r.

**Comment by rnorris** [comment]
It's in the file vikwindow.c in the selecttool_click() function, towards the end after the ' ( event->button == 3 ) ..' part as this is handles right clicks.
You can simply change the timeout line to directly call the show menu functionality, i.e.

    t->vw->show_menu_id = g_timeout_add ( timer, (GSourceFunc)window_show_menu_timeout, t->vw );
-->

    window_show_menu_timeout(t->vw);

**Comment by roooots** [comment]
Thanks - working nicely and perfectly suits my current usage scenario.


Cheers,
r.
