### ISSUE TITLE
yourscar routing broken because yournavigation.org is (permanently) down

### ISSUE THREAD

**Issue by omeckman** [viking-gps/viking#116]
Hello,

see https://forum.openstreetmap.org/viewtopic.php?id=735&p=11

It seems the original owner of this service isn't responding anymore.

I understand this has nothing to do with Viking itself, but i read it is wanted to have a working default routing service in Viking.

Maybe there is a quick fix to get it to work with router.project-osrm.org or some other service?

I came as far as adding this to the routing.xml:

```
<object class="VikRoutingWebEngine">
    <property name="id">osrm</property>
    <property name="label">OSRM</property>
    <property name="format">???</property>
    <property name="url-base">http://router.project-osrm.org/route/v1/driving/</property>
    <property name="url-start-ll">%s,%s</property>
    <property name="url-stop-ll">;%s,%s</property>
    <property name="url-via-ll">;%s,%s</property>
</object>
```

**Comment by rnorris** [comment]
The brouter option should be available and still working.

Regarding OSRM, sadly they removed GPX format support ages ago:
https://github.com/Project-OSRM/osrm-backend/issues/1180
(So the OSRM option was removed in Viking)

So now the only have their output in JSON, which IIRC isn't any particular schema.
However if it is GeoJSON then with the current releases of GPSBabel should might work - try **geojson** for the format
(Since VikRoutingWebEngine passes returned results to GPSBabel to convert into something Viking can understand).

https://www.gpsbabel.org/htmldoc-1.7.0/fmt_geojson.html

If it is not GeoJSON, then specific code is needed to interpret the JSON returned. Unfortunately the above OSRM service doesn't seem to be working at the moment, so I can not check. NB probably better to use 'https' rather than just 'http' in the url-base.

Also the last time I looked there is some potential routino servers - but maybe per country only.
See https://sourceforge.net/p/viking/discussion/general/thread/9ddcea4bba/

**Comment by omeckman** [comment]
```geojson``` format did not work, I just don't get any console output when trying to create a route, would have to dig into the source code, but changing the profile from ```hiking-beta``` to ```car-fast``` in the brouter default profile did the job for me, works just as yourscar worked before (as far as I can see).

As a casual Viking user not into the depths of GIS software, in my mind, I somehow discarded ```brouter``` as the hiking version of routing without taking a closer look :)

```
  <object class="VikRoutingWebEngine">
    <property name="id">brouter</property>
    <property name="label">brouter</property>
    <property name="format">gpx</property>
    <property name="url-base">http://h2096617.stratoserver.net:443/brouter?nogos=&amp;profile=car-fast&amp;alternativeidx=0&amp;format=gpx</property>
    <property name="url-start-ll">&amp;lonlats=%s,%s</property>
    <property name="url-stop-ll">|%s,%s</property>
    <property name="url-via-ll"></property>
    <property name="url-ll-lat-first">FALSE</property>
  </object>
```

Thank You

**Comment by rnorris** [comment]
Yes sadly the **geoson** option doesn't work 'out of the box'.

However this has prompted me to have another look at the OSRM output, which with some specific code and modifications to the request - I now have a provisionally working solution - which I will seek to push to the mainline code base in the next few days after some tidy up and more testing.

I'm glad you've been able to use the configurable methods to get a different brouter profile to work.

**Comment by rnorris** [comment]
The latest code now has capability to process the JSON returned by OSRM services.

See commit - https://github.com/viking-gps/viking/commit/0bf136ef58301230bdefef4062821a91d594fe2e
