### ISSUE TITLE
Librem 5 showing Grey screen

### ISSUE THREAD

**Issue by programmin1** [viking-gps/viking#120]
Installed Viking on Librem Phone, and it has a grey background, not the Mapbox map. Am I missing a step for install?

**Comment by rnorris** [comment]
Are you using Viking 1.9?
The default map is now OpenTopoMap - the Mapbox free service is discontinued, otherwise try using different Map services selectable in the Map Layer properties.
Different/Additional Map services can be added via manual configuration.
See the user guide and/or https://sourceforge.net/p/viking/wikiallura/Maps/

**Comment by programmin1** [comment]
I install 1.10 using Flatpak and this particular issue is resolved, thanks for updating.
