### ISSUE TITLE
No direction routing engines available

### ISSUE THREAD

**Issue by berkut-174** [viking-gps/viking#129]
Hi. When I start the application, I see the following message:

```
$ viking                                                                                                                 
** viking [Warning]): No direction routing engines available                                                                                      
(viking:215116): Pango-WARNING **: 8:52:59.370: Invalid UTF-8 string passed to pango_layout_set_text() 
```

At the same time, routing through OSRM works.
Should I be worried by the warning message?

**Comment by rnorris** [comment]
No one should not worry, as this is perhaps now a somewhat superfluous warning.

Previously I think it might have crashed in the past when there were no such routing engines available and the user attempted to use the relevant menu entry, so this was an improvement as the menu entry is now only enabled if necessary.

Viking has a concept of two types of routes - described internally as either by lat/lon or by 'directions'
Personally I'm not quite sure why it's called 'directions' - possibly better called 'places' - as in typically it's route like from 'London' to 'Paris'. (Possibly because it originally worked with Google Directions)
Whereas currently all the default routers being used are using lat/lon from positions clicked on the map so something like from 51.6,0.0 to 48.8,2.0.
The way the requests are made to the online router are handled differently - and as Viking is configured at run time by loading in the XML files - it's only saying there aren't any of the 'Direction' type.

If there are ones of the 'Direction' type - the menu entry File-->Acquire-->Directions... is enabled; 
which then gives you a dialog box to enter the From and To places.

The manual describes the routing.xml config file and the url-start-dir / url-stop-dir values.

HTH
