### ISSUE TITLE
Viking version 1.9 for Windows: Opentopomap tiles not downloading & therefore not displaying

### ISSUE THREAD

**Issue by ke-ss** [viking-gps/viking#139]
Have most recent version of Viking, version 1.9 for Windows, and Opentopomap tiles are not downloading.

Viking 1.9 will download OSM tiles and display these, but will not download and display opentopomap tiles.

Ideas anyone?

**Comment by ke-ss** [comment]
Here is the fix

1. close Viking application

3. Open file 
**C:/Users/<user name>/AppData/.viking/viking.ini**
if you search for the **viking.ini** file you will find it. 

4. ... and add the is line to the bottom of the file and save it
**curl_ssl_verifypeer=0**

5. Open Viking again and opentopomap tiles should now load

**Comment by rnorris** [comment]
I suspect the real reason is that Viking uses libcurl which in turn accesses a certificate store to verify the HTTPS certificate against and this is failing - i.e. getting **curl error: 60 for uri...** messages in the message log.

AFAIK For Viking on Windows this certification store (I'm not even sure where this is - if there is even one - there could be some defaults built into the curl library itself) can only be generated at build time - and then is not updated any further. Thus these verification methods can have expiration dates and can start to fail - hence the above disabling of the verification gets the Tiles working again.

For background reference on certificates see here (especially the first part):
https://ubuntu.com/server/docs/security-certificates

For most versions of Linux - this is handled at a system level and are periodically updated - such that individual programs don't have to manage this certification update.
I assume for other Windows programs - e.g. web browsers - they update often (and have teams of people who can manage such things) and include updates to certification stores.

Viking on Windows has no such luxury or support. And further I think there is difference in binary format between Linux and Windows - such that I can't simply copy the latest file(s) from a Linux system and install them on Windows either.

I'll think about turning off the SSL verification in the Windows build - if that means the default (OpenTopoMap) Map service works by default.

**Comment by ke-ss** [comment]
Hi Rob
Thanks for the reply.
I suspect that most people are using Viking as a hiking app which makes OpenTopoMaps essential.
In other words, without effective hiking maps folks will do a quick uninstall and move on.
I would simply turn off the https certification, becasue it is turned off in any case to get it working as outlined in the fix (above).
It will save a lot of hassle.
(I installed this on a friends Windows laptop but use Linux myself where the Viking app works flawlessly)
