### ISSUE TITLE
Incorrect GPX output and lack of support for some elements

### ISSUE THREAD

**Issue by zimbelstern** [viking-gps/viking#143]
Thank you for creating this software!

I am using Viking 1.10 built from source and have noticed the following issues regarding GPX exports:

1. The `<name>` element is a direct child of `<gpx>` but it has to be inside `<metadata>` according to the GPX specification.
2. The _URL name_ of waypoints does not appear in the GPX file, unfortunately. It could be printed to `<text>` inside `<link>` .
3. It would be great to have the mime type of the linked image inside `<type>` when `<link>` is a reference to the waypoint image.

**Comment by rnorris** [comment]
Thank you for reporting these issues.

1. Yes this a mistake - for GPX1.1 (which is now the default and has only been available from v1.9 onwards). Note that `<name>` element is a direct child of `<gpx>` is valid for GPX1.0.
2. Viking doesn't currently read in `<link><text>` values for GPX1.1, so nor does it write such a value on export. Currently the 'URL Name' on the Waypoint Properties->Extra tab is only used for GPX1.0 files. Viking can be updated to support URL Names in import/export from the `<link><text>` GPX1.1 style.
3. OK. 
In creating the mime type value, I'm initially thinking doing a very simplistic string match along the lines of if the link ends in (case insensitive) '.png' then type is "image/png" of if ends in (case insensitive) '.jpg' then type is "image/jpeg". 
One might be able to properly determine the type via checking each linked file using e.g. [mimeinfo](https://metacpan.org/dist/File-MimeInfo) - if it is available.
Unfortunately I'm currently unaware a native C library way of doing this.
Even so invoking a command or function for each linked image file could be noticeably slow if there's many waypoints in the save.
Do you know of any software / service that uses this `<type>` value in GPX files?

**Comment by zimbelstern** [comment]
I don't know. I found Viking when I was looking for a software to create waypoints and routes on a map and annotating them with information like an image and a hyperlink with a description. I want to read this data by an external script and insert the information into a custom database. Looking at the Waypoint Properties window in Viking I expected the present fields to be exported in GPX as far as possible. However, in the GPX export, both the image and the url become strings in `<link>` tags and the information that one is an image and the other one is a hyperlink gets lost.
Viking knows that the image is an image. A simple solution from my point of view would be to use `image/*`as a mime type if Viking does not know the exact image type but as far as a know this is not a correct mime type. I don't know how Viking recognizes an image in a GPX file exactly (you could only _guess_ that it is the image and not the url) but from what I see, Viking itself is a software that cares about the type of a `<link>`. ;-)
However, now that I know what is working in which way I've found some workarounds. I swap `<metadata>` and `<name>` in my python script and I "misuse" `cmt` and `src` for the 'URL' and 'URL name'. So these issues are not critical for me.

**Comment by rnorris** [comment]
> However, in the GPX export, both the image and the url become strings in <link> tags and the information that one is an image and the other one is a hyperlink gets lost.

Viking expects the image associated with waypoint to be a local filename reference - typically initially set via the `Browse...` file system button (I don't think it will display the image if one inputs an HTTP style URL reference in this field).
Whereas the `URL` is expected to be a "URL" - i.e. something beginning with "http..."

Currently when exported into a GPX file the image gets saved as `<link href="file://...">`, whereas the URL should be `<link href="http...">`. Then when reading in from a GPX file the link href field is examined, such that file:// references get put into the image property and http ones get put into the URL field.

ATM Viking doesn't care about the type of a link. Indeed the URL link could be pointer to an image, so I don't think it necessarily helps in reading it in.

Further as you have found since one can put any string into `cmt`, `src` or `desc` fields - people do put URLs in there - so that's why I made those labels clickable links too.
