### ISSUE TITLE
OSM: display place names in latin letters?

### ISSUE THREAD

**Issue by roooots** [viking-gps/viking#145]
Hi,

I'm wondering if it's possible to make OSM/Mapnik show the names of places etc. in latin letters in Viking? Or in both native and latin writing, like with OSM/Cycle for example.

Any suggestions welcome!
r.

**Comment by gdt** [comment]
This isn't really a viking issue.   You can choose any tiles you want.  OSM's default tiles (probably best called something else because mapnik is a tool, not a style, but I know what you mean) localize names in the country's langage.  There are other tile providers and one of those may be what you want.   But most importantly, labels in tiles are pre-rendered by the tile provider so there is absolutely nothing viking could do about this.

You could set up a tile rendering instance on your own computer and run a modified style to render in whatever language/letters you want and use that.  But it's a lot of work.

**Comment by roooots** [comment]
Ok thanks, I wasn't fully aware that these came pre-rendered with the tiles. I'm using OSMAND-HD by default, where the names are localized in the country's language. Unfortunately other tile providers like OSM/Cycle do not provide HD tiles, so that's not an option. Do you have any suggestions for alternative HD tile servers?


Thanks,
r.

**Comment by gdt** [comment]
no, sorry, and probably best to hit close as this is not a bug in viking
