### ISSUE TITLE
Not using exact GPS on Librem 5 phone

### ISSUE THREAD

**Issue by programmin1** [viking-gps/viking#148]
The auto location feature doesn't seem to use exact GPS on my Librem 5 phone. Auto location shows another area in the neighborhood.
Can this add a blue dot to the map in the same manner as GNOME Maps app does please?
The app seems quite full featured but it should have the GPS of the device considered, otherwise it doesn't work so well for mobile use.

Also, the menus and preferences are not all accessible, for example when you go to Advanced -> Select Newly created.... has no way to see that option or check it.
This is Viking 1.10 from Flathub.

**Comment by gdt** [comment]
Can you point to the documentation for the location API on the Librem 5?  It seems sort of GNU/Linux, sort of some GNU/Linux+PHONESTUFF.    Is this just gpsd?

**Comment by programmin1** [comment]
It is desktop Linux yes.

**Comment by gdt** [comment]
But "desktop GNU/Linux" does not have a defined location API.   You need to explain that, and you need to use a test prorgram to verify that the API is working.  And then to read the viking docs to see if it is supported, and then to debug :-)

**Comment by programmin1** [comment]
systemctl | grep GPS shows

gnss-share.service

active. Geoclue gets the neighborhood most times but it looks like right now GPS isn't giving exact location...

**Comment by gdt** [comment]
So if there isn't a GPS location, it doesn't seem like a viking bug not to obtain it?

**Comment by rnorris** [comment]
Closing this issue as GPS location is from the GeoClue service, so not specific to Viking.
Improved the preferences dialog to enable access all parts of it on small screens.

If there is an explicit menu problem with Viking on small screens, feel free to create a new issue; However note that how menus are displayed is up to the windowing system, so if the menu is too big too fit it should enable some scrolling or other mechanism to enable access to all menu elements. I don't think it would be appropriate for Viking to try to limit menu entries (or use some alternate selection method) when it is intended for Desktop use, rather than phone usage.
