### ISSUE TITLE
GeoRef layer incorrect limitations

### ISSUE THREAD

**Issue by pawelpbm** [viking-gps/viking#149]
I georeferenced image file and generated world file, but I'm not able to import it into Viking.

World file I have is as below:
```
10.07889441400585007
0
0
-10.06641546013836397
2112543.75589477084577084
7180091.77272090781480074
```

Unfortunately Y scale doesn't accept any values below 0.03125000 (it reverts to this value when I type in -10).

Additionally "Corner pixel easting" is limited at 1500000.0000. I believe this one is caused by value here [1] being one 0 shorter than [2].

[1] https://github.com/viking-gps/viking/blob/7f67c86e4c254fbf7cf707e4de7f1d364d838b56/src/vikgeoreflayer.c#L887
[2] https://github.com/viking-gps/viking/blob/7f67c86e4c254fbf7cf707e4de7f1d364d838b56/src/vikgeoreflayer.c#L891

**Comment by rnorris** [comment]
Thank you for raising this issue.

I wouldn't go quite as far to say the layer is broken, but perhaps it doesn't work as well as it should, so I have taken the liberty to rename this issue.

It seems both these limitations have been in Viking from it's inception - and agreed that the Y scale should accept negative values and that the Corner Pixel Easting should allow values to 15_000_000 - i.e. six zeros and not 1_500_000.

**Comment by rnorris** [comment]
So I've had second thoughts about the Y scale...

Viking has somewhat incorrectly been treating the Y scale as an absolute value (similar to the X scale). Since it doesn't support 'upside down' images, the Y value is taken as the scale of the image regardless of the direction - i.e. it has treating the +ve Y value incorrectly as the -ve value; and -ve values are converted to a +ve value for the internal workings.

However for compatibility with any existing Viking's own GeoRef layer saved file values, I'm not going to make it strictly 'correct' to the World File conventions of the meanings of +ve vs -ve Y scale values; and/or start handling 'upside down' images.

The corollary is Viking should:
1. Ensure writing a -ve Y scale value, in the World File export.
2. Add some notes to the manual to explain Viking's behaviour regarding the Y-scale behaviour.

So currently your World File should be read in OK (either via the auto load associated world file for the 'Map Image' mechanism or by the 'Load From File...' button) - since the -ve Y-scale value will be converted into a positive value, but you can't directly input a -ve value in the GUI.
