### ISSUE TITLE
Please support GPX files compressed with gzip or xz

### ISSUE THREAD

**Issue by vinc17fr** [viking-gps/viking#160]
Support of zip and bzip2 files was [added in Viking 1.8](https://sourceforge.net/p/viking/news/2020/02/viking-18-released/). Likewise, Viking should support files (at least GPX files) compressed with gzip or xz (which are nowadays much more common than bzip2).

**Comment by rnorris** [comment]
Just for background information, bzip2 support was needed internally since it is needed for the `My OSM Traces` features as files returned via the OSM server may be compressed via bzip2. And thus only a few lines needed to make it easily selectable at the UI level.

I'm working on xz support (I have got it working on my PC) and so will seek to upload soon after more extensive testing.

I haven't looked to hard at gzip yet, but provisionally that looks quite straightforward since we already use zlib - which seems to be way to uncompress the files.
