### ISSUE TITLE
Describe "automatic internet features"

### ISSUE THREAD

**Issue by jonasstein** [viking-gps/viking#168]
It is not clear for the user what "automatic internet features" are.
Please use a more specific/clear term, or describe what is activated here and what data is transferred.

![2023-01-26_screenshot_f8415d26](https://user-images.githubusercontent.com/298682/214715832-26666667-ed69-4606-b5b4-b3887f5716f1.png)

**Comment by rnorris** [comment]
The intention in the message is to be more abstract than a concrete list of specifics,
as otherwise a simple message for convenience will become long and convoluted.

Furthermore changes to such messages would also need to maintained across all the internationalized translations.

Given the nature of the Open Source program, users are empowered to inspect the source code if they do not trust the supplier.

Viking enables at least these facilities, depending on the operations or files loaded by the user; using a default set of service providers and is configurable to enable different service providers at the users discretion:

* Requests for Map Tiles for the current viewport
* Requests for Route Directions during Find Route operations
* Search Location requests
* GeoLocation dependent on the IP address

These should all be covered in the User Manual if the user wants more information.

**Comment by KIMWW** [comment]
I clicked on NO but since no maps are shown, now how can I activate internet features ???
I searched in Preferences but I have not found anything related to internet connection!!!

**Comment by rnorris** [comment]
IIRC - when you select 'No' 
The Maps Layer will default the property `Autodownload maps` to Off.

Thus for every Map, in the left hand panel, right click -> Properties -> 'Autodownload maps' -> Tick Checkbox -> OK.

You can subsequently change the Map Layer default via the Main Menu -> Edit -> Layer Default -> Map...
(which is then used for every time you create a new map layer).

HTH

**Comment by rnorris** [comment]
That's the properties of the `TrackWaypoint` Layer.

You need to add a Specific Map Layer (I forgot that when 'disable internet features' is turned on - a default map layer is not added - see Edit->Preferences->Startup->Add default Map layer - to turn that on).

To manually add a Map Layer - for example - In the left hand panel - right click on the Top Layer->New Layer->Map

**Comment by KIMWW** [comment]
It seems to be connected to internet now: (viking  TCP I:33066->server-52-222-174-39.cdg50.r.cloudfront.net:https (ESTABLISHED))

But still no maps. It says : Mapbox Outdoors: Failed to download tile

**Comment by rnorris** [comment]
Mapbox Outdoors (free) service has been discontinued.
What version of Viking are you using?
Try another Map Provider
