### ISSUE TITLE
No auto download of expired map tiles

### ISSUE THREAD

**Issue by roooots** [viking-gps/viking#170]
Hi all, 

I'm running Viking 1.10 on Ubuntu Linux. I'm using OSMAND HD maps, have set cache expire age to 5 and autodownload maps enabled. When enabling "Toggle Display of Cache Status", I'm getting mostly "red" tiles, but Viking won't auto download the updated tiles unless I use "Download new onscreen maps", which properly updates the tiles within a couple of seconds. It's not that it fails to auto download, it doesn't even cue the tiles ("0 items") in first place.

Any ideas why Viking won't auto-update the tiles?

r.

**Comment by rnorris** [comment]
First, apologies for such a late response.

I think if the cache status is 'red' (as opposed to dark red) - then it means it thinks there is no file on disk.
As you are using HD maps there might be scope for some discrepancy between the cache / when to download / what is displayed / viewport scale - which perhaps get sorted by the manual forced "Download new onscreen maps".

I'll have to investigate further...

**Comment by rnorris** [comment]
A preliminary investigation reveals there is a probably a mistake in the `download.c` download() function.

It can return early if map properties 'check_file_server_time' and 'use_etag' are both false  (as can be set in the relevant map type XML property configuration in the `maps.xml` file) as it then doesn't even perform the local file cache age tests.

A temporary work-around should be to set check_file_server_time for the appropriate map type by adding this line into your maps.xml file, as I'm guessing it is not set (the default when not specified is FALSE):

    <property name="check-file-server-time">TRUE</property>

Note that I could not reproduce it failing via the autodownload methods. However when using the Map Download Tool and then right click on an individual map tile -> "Redownload All Maps(s)" or via 'F5' - it did not work for my OSMHD map config.
So I'm hopeful this is the root cause of the autodownload issue.

**Comment by roooots** [comment]
Hi, thanks for looking into this and for quickly providing a work-around suggestion! I guess I was not the only one worried you may have dropped the project ;-)

Setting 
`<property name="check-file-server-time">TRUE</property>`

in `map.xml` indeed does the trick for me - tiles are loading / updating fine again now! This solution is much appreciated!


Cheers,
r.

**Comment by rnorris** [comment]
My latest thinking is to probably scrap 'check_file_server_time' test in download(), since this merely passes this option on for use with (lib)curl.
And a corollary is to change the check_file_server_time to TRUE by default for all map tile services.
I can't think of a reason why you wouldn't want to put that in the download request by default, so this should be an opt out option, not an opt in option!

**Comment by roooots** [comment]
Ok I see. This probably doesn't have very high priority as we have a workaround now, but if I can assist in further testing, please let me know! 

r.
