### ISSUE TITLE
Newlines in the exported GPX

### ISSUE THREAD

**Issue by sandaihu** [viking-gps/viking#176]
Exporting a project to the `GPX` format adds newlines after the `version` and `creator` of the  `gpx` tag

> <gpx version="1.1"$                                                                                                                                            
creator="Viking 1.10 -- http://viking.sf.net/"$                                                                                                                
xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3" xmlns:wptx1="http://www.garmin.com/xmlschemas/WaypointExtension/v1" xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v2" xmlns:gpxpx="http://www.garmin.com/xmlschemas/PowerExtension/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www8.garmin.com/xmlschemas/GpxExtensionsv3.xsd http://www.garmin.com/xmlschemas/WaypointExtension/v1 http://www8.garmin.com/xmlschemas/WaypointExtensionv1.xsd http://www.garmin.com/xmlschemas/TrackPointExtension/v2 http://www.garmin.com/xmlschemas/TrackPointExtensionv2.xsd http://www.garmin.com/xmlschemas/PowerExtensionv1.xsd">$

Usually HTML/XML tag attributes should be on one line, could those newlines be removed (or not added) during the export?

Thanks.

**Comment by rnorris** [comment]
"Usually HTML/XML tag attributes should be on one line."

Although this may be unusual, this is how Viking has worked since it's inception.

AFAIK new lines can be practically anywhere in the XML, thus if you have other software that can not handle this - then is it a problem with that particular software. All programs and services I have used have not had such problems with GPXs created by Viking.

So I would like more compelling evidence to suggest Viking is 'wrong' or suboptimal; rather than perhaps just a cosmetic issue.

**Comment by sandaihu** [comment]
Agreed, not saying it's a priority issue or breaking anything, only a format observation.

**Comment by rnorris** [comment]
Well I've changed now, although I accidentally made a typo in the commit reference to be under #178 instead of #176. D'oh!
