### ISSUE TITLE
move wiki and UM to internal page

### ISSUE THREAD

**Issue by axd1967** [viking-gps/viking#178]
Wiki pages seem attractive to use, but suffer from a versioning flaw: they are not synced to sourcecode changes.

Ideally, wiki pages should be updated with every release, or even better, as part of every issue.

A solution is to move these wiki pages into the source code repository and forget about the wiki concept, or use it in a different way (but which way?).

Same issue for the User Manual - it logically evolves with code changes and should therefore be present inside the repository.

One concrete use case is to be able to consult a specific version of Viking: I currently have 1.7 installed, am looking at https://sourceforge.net/p/viking/wikiallura/Version-1.7/, but am have access to UM 1.10 only.

![image](https://github.com/viking-gps/viking/assets/3529789/45e856ed-d23c-40ad-af77-52de1f43665c)

(slightly related: the "files" link on https://sourceforge.net/p/viking/wikiallura/Version-1.7/  actually links to the most recent version, which is wrong)

**Comment by rnorris** [comment]
Wiki pages are specifically not in the source code repository for a few reasons, including:
. Potentially editable by anyone (although need to be pre-approved to protect from vandalism and possibly need a SourceForge account).
. Lifecycle of information not necessarily related a specific code version.
. Means you can actually see it with a web-browser and can be indexed by search engines.

So I don't see a compelling reason to change.
Anything in the Wiki that is version specific can be stated to be so.

The User Manual is in the source code - see directory `help/C` and is meant to be aligned to the current version of the code. A wiki-ized version of the latest UM is put in the wiki as a optional convenience - but since it's quite large and not really optimized for use in the wiki (no images, cross-references don't seem to work, etc...), only the latest one is stored.

The files link mentioned above - goes to the general SourceForge file download page - which contains all 'recent' versions. The download page may automatically offer the latest version by default - but the full list should be viewable.

The files download (as of about 2 days ago) now also contains older versioned copies of the User Manual - in PDFs.
Releases on Github also contain a PDF copy of the user manual (although I forgot to put this in the v1.7 release).
