### ISSUE TITLE
--map argument ignored

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#190]
--map 13 is supposed to choose Mapnik, etc. But none of the numbers I tried have any effect. It just stays opentopomap no matter what. Debugging shows indeed other tiles are attempted to get fetched, but still opentopomap is what's on top!

Perhaps that's intended, but what users expect is just simply choosing a different background.

Version: the latest one on Debian sid.

**Comment by rnorris** [comment]
Yes showing the map as specified on the command line is what I intended! 

Unfortunately the Preferences->Startup->Add a Default Map Layer (which is defaulted to On) - seems to win and so that Map is shown on top. So it 'works' provided that option is turned off.

However, of course when the map is specified on the command line it should override that preference.
