### ISSUE TITLE
Not all input is GPX these days

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#206]
Man page says:
>        -e, --external
>           Load all specified GPX files in 'external' mode.

What about KML, etc.? Maybe above just remove the word "GPX".

**Comment by rnorris** [comment]
Actually due to the specifics of the implementation - this 'external' mode only works for GPX files.

Separately I have been thinking about making this work for any supported file type, but there is a little wrinkle I've yet to decide how to best proceed. 

Currently this external mode loading is performed in the TrackWaypoint layer - which is OK for GPX files since they only have straight-forward geodata - tracks/routes/waypoints, whereas for KML, TCX and FIT files potentially have 'container' level grouping information - much like how Viking's Aggregate levels work.

This probably means I'll have to add the External file properties (as used in the TrackWaypoint layer)  to the Aggregate layer as well.

**Comment by rnorris** [comment]
External mode is now enabled for main file types since commit: fd4e29da38b0b1ccee135ee810782b9d78eabdfe2
