### ISSUE TITLE
Viking can't find gpsbabel

### ISSUE THREAD

**Issue by ravl1084** [viking-gps/viking#23]
Hi,
I started using Viking and I'm trying to download tracks from my Garmin. I installed the latest gpsbabel, and in the Viking preferences I set the executable for GPSBabel to `/usr/bin/gpsbabel` but I still get a message saying that GPSBabel cannot be found when I click 'Download from GPS'.

Any ideas?

**Comment by rnorris** [comment]
Which Garmin device is it?

Most "modern" (i.e. last 5 years or so) Garmin devices Etrex 10/20/30 etc... no longer transfer data over the serial link (one reason to use GPSBabel). Normally now ensure the Garmin device is set to 'USB Mass Storage' mode or similar and it should get mounted on your computer - typically /media/<username>/GARMIN.

Then one's tracks are in /media/<username>/GARMIN/Garmin/GPX/Current

Otherwise not sure why Viking doesn't recognize GPSBabel.
Presumably 'Download from GPS' you mean Acquire->From GPS...

Please copy the exact error message if this is still an issue.

HTH.

**Comment by ravl1084** [comment]
That makes sense. I thought that the GPS layer option for Garmins was going to navigate into the folders. Using the  Acquire->From file... menu is working well.
