### ISSUE TITLE
Preferences: increase precision of Default latitude and longitude coordinates

### ISSUE THREAD

**Issue by starnutoditopo** [viking-gps/viking#234]
In the `Preferences` window, the `Default latitude` and `Default longitude` fields allow only 2 decimal places.

![image](https://github.com/viking-gps/viking/assets/1422525/5adb02a8-8033-4b65-8107-1e224b66a0f5).

Some more decimal places (al least 5?) would be useful.

**Comment by rnorris** [comment]
I think the intention is more to show the location in a 'friendly' manner (and refine via the up/down buttons) - rather than perhaps a really precise location down to say an individual house. You can also set the home location via the menus: Edit->Set Home Location (which will use the current viewport centre).

Note that you can type in a more precise values like 1.2345, which will be used - even if the value displayed is rounded to 2 decimal places.

This display is controlled by the values in `globals.c` lines 70+71
