### ISSUE TITLE
Man page needs to update every time maps.xml updates, so it has the full current set of map ids

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#236]
The Man page says:
```
       -m, --map
           Add a map layer by specifying the map id. The value needs to match
           one of the internal ids or an id from the maps configuration
           extension (see below). Specifying a value of 0 will use the map
           layer default.

               Internal Map Ids:

               OSM Mapnik = 13

               OSM Cycle = 17

               OSM Transport = 20

               OSM Humanitarian = 22
```
Well, the man page needs to be updated every time the rest of the
program is updated.

That way the man page can have the same full current list as /usr/share/viking/maps.xml,
```
 13 OSM-Mapnik
 17 OSM-Cycle
 33 OSM-Cycle
 65 OSM-GPS
 29 CyclOSM
101 CalTopo
600 OpenSeaMap
701 Waymarked Trails Hiking
702 Waymarked Trails Cycling
703 Waymarked Trails MTB
704 Waymarked Trails Inline Skating
705 Waymarked Trails Riding
706 Waymarked Trails Riding
801 4UMaps
901 OpenTopoMap
```

without the user needing to poke around and visually parse that file to
dig them out.

**Comment by gdt** [comment]
If you mean to ask that the man page be updated dynamically when the system data/maps.xml is changed, then that is unreaosonable and inconsistent with packaging norms.    Also, if users/admins are intended to modify maps.xml, it belongs in etc not under share.

If you mean "the distributed maps.xml contains the following maps that are not in the man page" and you mean this as a bug about the man page that is in the repo, please say that.  And perhaps even a PR.

If you mean "I suggest an enhancement where the man page will be dynamically generated at build time to include the maps in maps.xml", then please say that clearly instead.

If you mean something else, I suggest that it needs to be clearer....

**Comment by jidanni** [comment]
> "I suggest an enhancement where the man page will be dynamically generated at build time to include the maps in maps.xml"

Yes, that's what I mean. Thanks.

**Comment by rnorris** [comment]
Note that a few entries in the  /usr/share/viking/maps.xml are actually commented out, since these are built in and are defined in `map_ids.h`. 
The ones in the man page/manual are intended to match the used ids in map_ids.h - although, oops, it is missing some entries (at least Bing Aerial=212, OpenTopo=901, BlueMarble=15).

>"Also, if users/admins are intended to modify maps.xml, it belongs in etc not under share."

Users/admins are **not** expected modify the one in /usr/share (i.e. within in $XDG_DATA_DIRS) - this is for the applications own deployment; although of course an admin can change it they want.

Users are intended to (create)/modify their own maps.xml if they want to define additional map services, which is in ~/.config/viking/

Auto-generating the man/manual from *both* the map_ids.h and maps.xml would be nice; but would require several advanced features to do so:

1. Have some way of marking unused entries in the map_ids.h - e.g. as it contains references to discontinued map services (I suppose these could just be commented out in the code)
2. Handle commented out C code and commented out XML code, which makes otherwise simple scripting with grep/sed difficult as it needs understand that syntax.

So I think just need to be more vigilant in updating the manual vs map ids used - including those in maps.xml
Note the intention is that map ids never change for a named map instance. 
Map instances may get added or removed - but this is fairly infrequent - so manually updating the manual is not much of an overhead - of course providing one remembers to do it...
