### ISSUE TITLE
Have --map with no ID print the current IDs available

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#238]
I have a better idea than #236.
Instead of the never ending task of hardwiring the current list of map ids into the man page, which eventually will grow and grow engulfing the man page... instead don't print any on the man page, but have e.g., --map with no parameters print the current list to STDOUT.

It could even break the list into groups depending on what file the info is coming from... or even if the info is coming from a "network source", whatever.

**Comment by rnorris** [comment]
In principal agreed, that the Map Ids can be made available programmatically.

However due to the way the command parameters are processed first (and by GTK library API) it is difficult to tell which if the map parameter has not been given (not without having to reprocess the parameters - which is point of offloading that on to the GTK API). Further the parts of program that determine the full list of available ids, happens somewhat later in the startup sequence. So to make it know enough to display what the map ids are, would need more convoluted startup sequence.

I think it would be simpler to implement a new dialog in the main program - say under the Help menu -> 'Map Ids' that lists the available Maps and their Id. Which has general purpose usage/awareness.

**Comment by jidanni** [comment]
Also when one hits the map type chooser
![Screenshot 2024-01-23 20 38 02](https://github.com/viking-gps/viking/assets/1230959/6ba17cbc-bf78-49c3-828b-d1450f861a28)
The list that appears (which is hard to take a screenshot of)
could have the numbers to the left of each item.

**Comment by rnorris** [comment]
I believe having the Ids available via the Help menu is sufficient.
Trying to add the Id into the Map chooser is difficult - due to the way that all layer properties dialogs are generated in a generic manner from the Layers properties. Thus would need some bespoke effort and/or extra complexity just for the Map type use, so not really in scope for a simple change.
