### ISSUE TITLE
CTRL+- zooms out, CTRL+SHIFT++ zooms in. Please also have CTRL++ zoom in

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#243]
In viking CTRL+- zooms out, just like other map programs and internet
browsers. But CTRL++ does nothing. One needs CTRL+SHIFT++ . Apparently
the logic is that CTRL++ is actually CTRL+= . True as that may be,
this mind warping complication, (first time I ever encountered it in
all my computing years) should be removed, please. Yes, even if the
user can remap it himself. Anyway having two keys bound to zoom in, but only one to zoom out, is OK too.

Oh yes, do also implement CTRL+0, which resets to the default zoom.

**Comment by rnorris** [comment]
NB Ctrl+'keypad+' does zoom in.
To invoke a standard '+' on keyboard you have to press shift.
Thus Ctrl+'+' does zoom in.

Consider some graphics software (on my Debian system) - AFAIK not changed from default configuration:

1. eog v45.1 (Gnome Image Viewer)
- Ctrl+'=' Zoom In
- Ctrl+'+' Zoom In, Ctrl+'-' Zoom Out

2. krita v5.2.1
- Ctrl+'=' Does nothing
- Ctrl+'+' Zoom In, Ctrl+'-' Zoom Out  

3. Gimp v2.10
- Ctrl+'=' Does Nothing
- Ctrl+'+' or Ctrl+'-' Does Nothing
- '-' Zoom Out
- '+' Zoom In (i.e. 'Shift=')
- '=' Does nothing

5. ristretto v0.13.1 (XFCE Image Viewer)
- Ctrl+'=' Zoom to fit Window
- Ctrl+'+' Zoom In, Ctrl+'-' Zoom Out  

4. geeqie v2.1
- '=' Zoom In. Or Shift+'='.  But Ctrl+'=' does nothing.
- '-' Zoom Out. Or Shift+'-'.

Interestingly Ctrl+'+ in Viking has been the Zoom In way since its inception.
Personally if I use the keyboard I  tend to use the Ctrl+Keypad for zooming, so never really noticed the '+' vs '=' issue much.

I do agree that usability wise Ctrl+'=' should zoom in.

And yes. CTRL+0 can be made to restore to the default zoom. This seems a fairly common way to set zoom to '100%'.

**Comment by jidanni** [comment]
Actually by sheer numbers of users, the bindings of web browsers should be the ones to emulate. No keypad on this laptop.
