### ISSUE TITLE
Checkbox nested in weird horizontal slider

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#248]
In some menus we see checkboxes seemingly nested in weird non-functional sliders. Second checkbox here:

![weird_horizontal](https://github.com/viking-gps/viking/assets/1230959/ced776f5-d254-4711-ada8-f4455fca91ca)

However as you also see above at the first checkbox, other checkboxes look normal.
In any case they all function OK, just some of them look weird.

viking 1.10

**Comment by rnorris** [comment]
I believe the 'weird non-functional sliders' is an indicator of the currently selected widget.
So if you press the tab or arrow keys it moves the focus to the next appropriate input widget and so on.

As all these widgets on the right hand side of these dialogs are set to expand to use the available space, GTK seems to in it's wisdom, extend that internal indicator of the current widget to the outer size of the widget - right up to the other edge - even for a checkbox that otherwise is just a bit of this space.

I'm not sure there is any way to control this better or if it is just a GTK 'feature'

**Comment by jidanni** [comment]
Indeed, doing TAB TAB TAB I see it yes is in fact the current TAB focus.

Well, OK, I'll get used to it. Thanks.
