### ISSUE TITLE
Viking horns + world icon

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#250]
Just the other day I was looking at the icons on the side of my screen, and saw this "world with a cellphone placed to its right" icon that turned out to be Viking's.

Well that is all well and good. Except being an icon, well it is rather hard to tell what is in it, due to small size.

That's when I had this super idea. Use instead a [Viking hat](https://www.google.com/search?q=viking+hat&tbm=isch), you know, with its signature curved horns, placed on top of the globe.

Or just a green globe with two curved horns protruding from the upper sides of its "head". The whole thing could be green: monochrome ready.

Anyway, then there would be instant identification with the app. Nobody would scratch their heads as to what app/program it was.

**Comment by rnorris** [comment]
Point 1 - I believe it is meant to be a hand held GPS unit - like the Garmin Etrex series, so not necessarily a cellphone.

Point 2 - Vikings didn't wear horned helmets, so I don't believe modifying the icon this way is appropriate.

https://www.historyextra.com/period/viking/historical-fact-check-vikings-myths-busted-did-wear-horned-helmets-violent-barbarians/

I'm not a graphic designer, so unlikely to come up with anything better. And besides the icon has been around since 2007 - so notionally there is some kind of 'brand awareness' for existing users.

**Comment by jidanni** [comment]
Oh gosh. I feel like a kid who has just been told the truth about Santa Claus.  I guess I'll just close the bug.
