### ISSUE TITLE
View all routes vs. Show all routes

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#251]
It seems both of these act the same so perhaps eliminate one.
![v](https://github.com/viking-gps/viking/assets/1230959/8a105372-ee28-4294-944f-a2f22a080166)

**Comment by rnorris** [comment]
**View All Routes** = This causes the viewport to move (and zoom in/out as appropriate) if necessary such that all routes in this TrackWaypoint layer can potentially be seen on the display. Each Route's visibility checkbox needs to be On in order to be actually shown on the display.

Whereas **Visibility -> Show All Routes**  = Ensures the _Visibility_ checkbox is turned On for all routes in this TrackWaypoint layer. It does not move the viewport.

Thus these do perform different actions
