### ISSUE TITLE
Interest in implementing running-friendly features?

### ISSUE THREAD

**Issue by davidedelvento** [viking-gps/viking#26]
I run (and I mean with my feet, not just I _run software_ on a computer :-) ) and I am considering to use viking to analyze my running data.

Problem is, most of of the things I need aren't implemented. I am interested in implementing them myself and submitting PRs, however before I go to that trouble, I'd like to know if there's chance for them to be merged, or if there is no interest in having running-friendly features in viking.

I guess the answer would be "it depends on the feature and how is implemented", so let's assume it's implemented with the same standard as the rest of the codebase, and I will submit two more specific issues as examples.

**Comment by rnorris** [comment]
Running friendly features in Viking will be gladly accepted.

Of course the more general purpose - like the graph smoothing - the better.

ATM I don't have too much spare time available to respond in more depth about the other Issues - in principle they look fine and sensible.

But I'd note a word of caution about the amount of effort required for 'plot extensions field in gpx data' since Viking doesn't handle really handle any extensions (i.e. fully supporting GPX 1.1). So I'd expect you need to create/extend the framework within Viking to handle such extensions and so your specific fields can be dealt with. Hopefully such a base would then lend itself for adding support for Heart Rate data etc... (see https://sourceforge.net/p/viking/feature-requests/96/ and https://sourceforge.net/p/viking/bugs/131/

**Comment by davidedelvento** [comment]
Great thanks, see PR #33 (and #32 however that is generic, not runner-specific)
