### ISSUE TITLE
KMZ, KML Properties' Metadata empty

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#278]
Here is [xinshe.kmz.gz](https://github.com/user-attachments/files/16029530/xinshe.kmz.gz). (I had to zip it (again) to attach it here.) It contains doc.kml which has a `<description>` etc. Alas, opening Viking's side panel and checking the Metadata part of the Properties of doc.kml, all we find is a date. All the rest are blank.

![Screenshot 2024-06-28 20 44 02](https://github.com/viking-gps/viking/assets/1230959/eb9638b1-ac50-4bca-96f9-8db15ddaada4)

Besides KMZs the same problem exists for plain KMLs too.

By the way, there isn't even a field, empty or not, for `<name>`.
It seems KML wasn't an expected file type when Viking was first designed.

**Comment by rnorris** [comment]
"It seems KML wasn't an expected file type when Viking was first designed."

Indeed.

The core of Viking, both internal data structures and most of the GUI display elements are aligned to each other and tuned to the capabilities of the GPX1.0 format and some typical extensions found in GPX1.1 usage.

Hence for KML (and FIT + TCX) formats - they are converted in a best attempt into what the core of Viking supports. Occasionally, the core is enhanced to support more items but since it is a fairly fixed set of capabilities - it is not very flexible in supporting differing format variants and/or self describing schema extensions.
