### ISSUE TITLE
Have zoom icon print error message

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#291]
See also https://github.com/viking-gps/viking/issues/290 .

Hit the "plus" icon, until one cannot zoom in further.
Well it should print a message "maximum zoom reached",
instead of seeming broken.

OK, maybe print it upon the **second** failed click, or keyboard zoom,
so we slower-learner users will know what is wrong, (while smarter
users will know right away themselves, and stop clicking in vain.)

In fact the zoom icons don't seem to change color to indicate "don't bother pressing me again".

**Comment by rnorris** [comment]
It can certainly be easily improved with suitable maximum zoomed out/in reached messages on keyboard shortcut and menu invoked actions.

However, to properly enable/disable zoom icons - is somewhat more involved - since it means tracking all methods zooming (including scroll events, specific zoom level requests, multiple clicking and so on), to ensure the menu action buttons are suitably enabled. 

So, I'm hesitant to do the latter in case of introducing errors - or will simply take longer to resolve to including testing various potential failure points.

**Comment by jidanni** [comment]
All I know is on https://www.openstreetmap.org/ it is quite obvious when no more zooming will work, as the button has changed color.

**Comment by rnorris** [comment]
Improved with suitable maximum zoomed out/in reached messages on keyboard shortcut and menu invoked actions.

However properly enable/disable zoom icons is left for future improvements
