### ISSUE TITLE
Accented characters break search

### ISSUE THREAD

**Issue by fancsali** [viking-gps/viking#293]
Going to the 'Goto' tab and typing in a name with accented characters reports 'Service Request Failure'. The same locality is found, if one replaces the accented characters with the unaccented variant.

Steps to reproduce:
- On the bottom left choose the 'Goto' tab
- Type in a search term containing an accented character (e.g. 'tiszaújváros') and choose 'OSM Nominatim' in the dropdown
- Observe there are no results, but an error message: 'Service Request Failure'

*NOTE*:  Typing the name without accents ('tiszaujvaros') works. However, that's not really the same name, in languages that use accents do use it for a reason - i.e. accented and 'normal' characters are _different_. It is wise to make the system find the same object even without accents though - I am by no means arguing against that.

*NOTE*: Choosing 'Geonames' as a source, will also work as expected.

**Comment by rnorris** [comment]
Further to  Viking's in Search tool usage of the function g_uri_escape_string() - there is a parameter 'allow_utf8' - which is set to TRUE. 

This means, accented characters which are UTF8 are specifically not escaped.

It took me several readings of g_uri_escape_string() documentation, to really understand what it meant / does - as IMHO the description is a little brief and doesn't have much in the way of examples there to aid understanding.

So, also then realizing that [URLS](https://en.wikipedia.org/wiki/URL) - as in web addresses - are specifically a restricted ASCII subset), whereas a 'URI' - as used in the GLib function - has wider scope and can handle other references (like for 'file://' resources and more). For those URIs - UTF8 is allowed, hence the option for the GLib function.

Thus changing Viking to set allow_utf8 to FALSE in g_uri_escape_string(), fixes this issue.

Looks like I broke it back in 2016 when I did: "Replace internal uri_escape() function with a glib version.", which went into Version 1.7 onwards, by not using the GLib function correctly.

I still need to think what that means for the rest of Viking's web requests, possibly nothing further - since most configuration with URLs are not currently in the GUI - the assumed 'advanced' user can manually apply the escaping if necessary. Like what one has to do already e.g. in the Map XML config "url" property, for the relatively common `&` in Tile related URL patterns has to be specified as `&amp;`
