### ISSUE TITLE
test_metatile fails on big endian

### ISSUE THREAD

**Issue by jbicha** [viking-gps/viking#62]
I recently enabled build tests for Debian's viking package. test_metatile now fails on the big endian architectures.

Build log excerpt
----------------------
```
FAIL: check_metatile.sh
=======================

FAILED: Meta file ./metatile_example/13/0/0/250/220/0.meta header bad count 1073741824 != 64

FAIL check_metatile.sh (exit status: 3)
```

Build logs
------------
Click Maybe-Failed

https://buildd.debian.org/status/logs.php?pkg=viking&ver=1.6.2-3.1

**Comment by rnorris** [comment]
Ah, it seems the Metatile file format is probably not meant to be "portable standard file type" but merely a rendering cache strategy for a webserver.
The code is heavily derived from OpenStreetMap mod_tile -> [metatile.h](https://github.com/openstreetmap/mod_tile/blob/master/includes/metatile.h:)

Here we can see the //meta_layout// structure - that is written to disk as a direct stream of bytes:

    struct meta_layout {
        char magic[4];
        int count; // METATILE ^ 2
        int x, y, z; // lowest x,y of this metatile, plus z
        ...};

Thus by using repeated __int__ types next to each other for x,y,z it becomes endian dependent on reading back in (and also compiler dependent as the `sizeof(int)` may be different too).

Since my metatile file example was generated on PC, it is in little endian format.
So then when the test program now created on a big endian machine it fails when reading the little endian style file.

The idea of having the capability to view Metatiles is still useful - albeit that Viking & the Metatile files will need to have the same endianess to work - as is probably typically the case.

So I think the best approach is to simply skip the metatile checks for big endian machines; and make a note about this endianess incompatibility in the manual.

**Comment by gdt** [comment]
Can't the test just generate and then read something?  That seems better than skipping test coverage.  But I realize it's harder, and ENOPATCH.

**Comment by rnorris** [comment]
The test metafile I used is a 'real one' from running mod_tile itself in a VM setup using the full OSM Rendering stack (i.e. as per the guide@ https://switch2osm.org/ - so PostGIS + an data extract of OSM data from GeoFabrik of England).

No doubt one could simplify that / avoid all together and generate a default blank metatile for some particular location to check that it can be read back in. However I'd need to (re)revise how it works to understand the generation side better and/or borrow the 'write' metatile code from mod_tile.

So maybe that's something to add for the future, but it won't be a priority for me any time soon.
