### ISSUE TITLE
Windows: maps.xml access

### ISSUE THREAD

**Issue by richardy2** [viking-gps/viking#68]
If I open Viking and then open a GPX file from within it, I have a full range of maps available, including openstreetmap with my API applied. However if I double click a GPX file in a different folder I only have a limited list of maps which does not include my default map so no map appears.
I had assumed this was a path problem to maps.xml but adding this to PATH does not help. Any ideas? Using Windows10 and Windows7 and the problem is the same with both on different computers.

**Comment by rnorris** [comment]
You should be (creating if necessary) editing the maps.xml in your home directory:

     C:\Users\<username>\.viking\maps.xml

I'm guessing you are editing the 'system' installed maps.xml, in something like:

    C:\Program Files\Viking\data\maps.xml

I think Viking can't find its own 'data' directory if run via a double click, as this must set the current working directory to the location of the GPX file and so the 'data\maps.xml' loading fails (as this is a relative path).

Viking uses multiple paths in trying to load maps.xml files (entries from each location are cumulatively added) - in order to combine the installed values plus the user generated ones.

Background information:
IIRC Finding the absolute path on Windows wasn't as straightforward as I hoped and so gave up and used the relative path - which at least works when opening Viking first.
NB On Linux this works by using system locations defined by environment variable XDG_DATA_DIRS, but this is not available in Windows.

**Comment by richardy2** [comment]
Thanks for your assistance. I fully understand what you are saying and I have now solved the problem by moving maps.xml to what you refer to as my home directory from C:\Program Files\Viking\data\maps.xml which is where, as you suspected it was. However the default installation has the data, lib, locale and share folders all in C:\Program Files\Viking\ Should all these also really be  in the  "home directory" C:\Users\<username>\.viking\ and if that is the case could the install program be modified to put them there in the first instance.
