### ISSUE TITLE
Question regarding "bluetooth gps" sharing from mobile phone

### ISSUE THREAD

**Issue by marksev1** [viking-gps/viking#7]
I have a bit of an unusual set up.. I use my phone to share gps data (nmea sentences) with my netbook via bluetooth. On the netbook side i use gpsd, which gets is data from /dev/rfcomm0 I believe.. Foxtrotgps app works with that kind of setup, does Viking work with that too? And how to set it up? Since I've read somewhere that Viking can only get data in from ttyUSB0?

It would be nice if I could use my current setup without changes with Viking. (phone gps->nmea->bluetooth->gpsd-> software to display position on map)

Cheers!

**Comment by rnorris** [comment]
Yes Viking supports GPSD.

You need to create a __GPS Layer__ and in the properties set up GPSD via the __Realtime Tracking Mode__ tab.
Here you can set the GPSD host and port (and other settings), although the default settings of localhost and port 2947 normally work.

Then __right click__ on the __GPS layer__ in layers panel (the list on left hand side) and select __Start Realtime Tracking__.

HTH.

PS: Not sure where you read about only ttyUSB, but Viking can also use ttyS (serial ports) - although I think they are only displayed if those ports are detected. However these are only for upload/downloading recorded data via GPSBabel (rather than the live data - then GPSD needs to be used).

**Comment by marksev1** [comment]
Good to know, getting that crash also on my Ubuntu netbook so waiting on new version.
