### ISSUE TITLE
Feaure request/assistance: Elevation Pane

### ISSUE THREAD

**Issue by yourealwaysbe** [viking-gps/viking#76]
I spent an afternoon trying to add a dynamic elevation display pane to the left hand side, where the calendar appears. My efforts are in [this commit](https://github.com/yourealwaysbe/viking-1/commit/aca501f6fbb2ae1ef5ce4c94cc31ed30532cfc7f). Here i am trying to add a vlp->elevation widget and add a drawn graph to it during update.

However, i completely failed to get GTK to draw anything. The code in the commit is using the code in viktrwlayer_propwin as a model. I also tried [this tutorial](https://developer.gnome.org/gtk-tutorial/stable/x2470.html) and also did not manage to draw anything.

This request is essentially to ask for advice getting started on this. In particular, how do i draw!

Thanks in advance for any suggestions.

edit: to give more information. Drawing on a PixMap is probably fine. The hard bit is transferring that to screen. I've attempted creating an image and adding it to the panel, both by creating the image from the pixmap (gtk_image_new_from_pixmap) and setting the image from the pixmap (gtk_image_set_from_pixmap), both to no avail. I've also tried creating a drawable instead of an image and then using the gtk_draw_drawable method. Also with a draw request at the end. At best i've managed to make a blank panel to appear. I don't know if it's copying the pixmap to the image that is not working, or displaying the image that is not working, or something else.

**Comment by yourealwaysbe** [comment]
Further attempts have resolved this. Sorry for the noise!

**Comment by rnorris** [comment]
Interesting.

I've always wanted to have the option to effectively embed (i.e. reuse the code as much as possible or similar) the full track properties dialog into a section below the viewport (possibly with some kind of auto hide manner when nothing is selected), as this would give a wider graphs to view - this is now very typical of various online viewers. And then also to have a two way update of the selected point along the graph <-> the point in the viewpoint.

I don't think I ever got around to trying...

**Comment by yourealwaysbe** [comment]
My current work on this has basically rewritten the elevation drawing code: i tried reusing the trwlayer_propwin code, but found it too tied up with the widgets data structure.

Embedding the properties below the viewport would be very nice in fact. Dockable dialogs like GIMP..

**Comment by rnorris** [comment]
So I've started to play around with embedding the properties below the viewport...
I don't really know how the dockable dialogs work, but any way I think the full properties is too big (high) so I'm working on using just the graph subset itself.
Thus far I've got something almost useable, but requires further tayloring and refinements to be properly useful not using excessive screen space:
- such as instead of separate labels for the readout information -> change this to a tooltip.
- Instead of tabs, a right click menu to switch the graph on view
- Instead of checkboxes, again use right click menu entries.
- Issues to be resolved from my initial implementation thus far:
  - Selected by the layers panel (ATM I've only done it after selecting a trackpoint on the viewport)
  - Only works between selected tracks if 'nothing' is selected in between - as ATM end up with multiple properties.
  - Getting the **resize** drawing working at all (and perhaps only drawing the graph on view, as opposed to at the moment it does them all regardless of which one is on display)
  - Decide how it should work/update when you start extending / splitting / combining and other edits of the track/trackpoints are performed.
  - An option to disable it like all the other View->Show-> <Screen Element> config.
  - And at least one for the future - the virtual trackpoint 'blob' highlight on graph view should have an equivalent in the main viewport.

The track properties dialog itself will remain and is intended to be unchanged, as it's useful to be able to open more than one at time to compare different tracks.

**Comment by yourealwaysbe** [comment]
Cool. I had also been playing. I more or less understand how the dockable dialogs work, though i'm not sure they're super important right now: they mainly allow you to move pages of a notepad to another notepad. You can also set up an action for when pages are dragged and dropped in the main window. E.g. create a new window for them.

I also spent slightly too long today finding a replacement for "configure_event" when the graphs notepad is in a vpanel rather than a dialog. "notify::position" on the vpanel seems to work, but the graphs were not detecting the window size correctly.

It sounds like otherwise you're further along than me. I can check out what you have done and try to help. Maybe with the resize issue? It sounds like that's something where i might be able to figure something useful out rather than competing with your coding.

**Comment by rnorris** [comment]
Work so far:

https://github.com/rnorris/viking/tree/MainGraph

Yes the redrawing is incredibly unobvious - ended up using the "expose-event"
Any selection method should work now - still need to decide more cases for when it should be closed (primarily when selecting a different layer)

Still need to consider how to handle when track is deleted (either directly or indirectly); probably will have to do the same as how the dialog method works - a pointer is stored in the track itself! not the cleanest implementation...

**Comment by yourealwaysbe** [comment]
This is cool.

Is it reasonable to connect the update of the graph to the layer update signal? I think this means that

- the graph can update dynamically when a track/route is updated
- if something like a delete occurs, it will refresh, detect there is no longer a track selected, and hide itself

For selecting the different kinds of graphs and enabling DEM display (useful when the route finder doesn't embed elevation info) there is plenty of horizontal space for options to the side of the graphs.

**Comment by rnorris** [comment]
Another update has been made.

Yes I'll need to think about using the main update signal.

The DEM option will definitely be included somewhere.

**Comment by rnorris** [comment]
Latest update made too https://github.com/rnorris/viking/tree/MainGraph

Practically complete - incorporated a hook into the emitted update function (rather than the actual signal) to notice when potentially the track has changed to recalculate axis and graph. This should avoid unnecessary redraws.

Still outstanding is an marker on the viewport map to show the pointer position from the graph.
But that may take a quite a bit more new code, rather than the mostly reworking of existing code.
I also want to properly understand the 'MARGIN_X' factor to optionally reduce/remove it, but its quite fundamental in the graph drawing ATM.

**Comment by yourealwaysbe** [comment]
Looks good. Thanks a lot for this! Sorry for being quiet -- work is hectic these days.
Should this work also when routes are selected?
It would be cool to show DEM data if it exists: during route planning elevation data isn't usually embedded by default, and it would be useful to see in real time how the elevation of the route looks.

**Comment by rnorris** [comment]
No worries, we all have our priorities.
Yes it should work when routes are selected - but sorry I overlooked this in the last code update; it will be fixed.
Elevation data when manually plotting a route is automatically applied; however if you use the route finder then ATM Viking won't add in DEM if it's not supplied by the route provider. That should be simple to remedy.
Another thing I'll try to add is showing this pane when creating a route; as ATM at first with no points it doesn't get shown - so you've have to add a point or two; finish it and reselect to show the elevations.
