### ISSUE TITLE
<extensions> tags in gpx file

### ISSUE THREAD

**Issue by ShelleyLake** [viking-gps/viking#77]
Please do not trash any `<extensions>` tags that may be present in the original gpx file.
I'm not asking to show and/or modify them in any way, but only to read, preserve and save them in the export of the gpx file.

**Comment by rnorris** [comment]
Unfortunately Viking only explicitly supports GPX1.0 which doesn't have any extensions.

This is hopefully made slightly apparent since you can not 'save' a GPX file directly, you have to 'export' to it.

Internally Viking processes GPX files into it's own understanding and then creates newly generated GPX format when requested to export to GPX. 

There have been requests for the common extension types (such as Power, Cadence & Heart Rate) which is likely to see some level of at least read support in the near future, however (saving) this might conflict with a reasonably simple approach to storing extension information as literal copy of the extension(s) as text for every point, track and gpx file.

Hopefully with enough thought there should be a viable solution that has a chance of being implemented.

**Comment by rnorris** [comment]
This commit addresses this issue.

https://github.com/viking-gps/viking/commit/d93a038f1394617be0c7c52cfd1e83395282c6ce

Further GPX1.1 items are in the pipeline.
