### ISSUE TITLE
Why must "pan" and "select" mode conflict?

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#87]
Why must "pan" and "select" mode conflict? Why cannot one do both
without needing to switch from one mode to the other? Isn't that how all
other mapping systems operate?

One doesn't need to switch to "zoom" mode (must be from back when mouses
didn't have wheels), and still be able to zoom (with the wheel) despite
being in "pan" or "select" modes.

That is a good first step. Now all that needs to be done is allow people
to select when in pan mode, and pan when in select mode.

Sure, keep the older functionality for people who only have some broken
mouse or something, but for the rest of us, please make sure the
interface acts like Google Maps or OSM.ORG or iD editor etc.

Sure with a giant screen one rarely needs to pan, so doesn't notice the
problem.

**Comment by rnorris** [comment]
It was done this way for both ease of implementation as well as to keep these modes relatively separate.

ATM you can make the select mode pan via holding down the Alt Left on Windows and possibly Alt Right (if this key is in the 'Mod 5' group) on Linux injunction with the mouse. 

Also see https://sourceforge.net/p/viking/feature-requests/124/
Seems I forgot to put this in the manual.

One notion behind using a key modifier instead of making this the default behaviour is that it avoids performing a lookup to see if any trackpoint/waypoint is at that position (which might possibly be quite slow - but doesn't seem to be in practise).

So it will be possible to make the select mode pan and possibly make this the default mode.

I'm inclined to keep the pan mode as is, otherwise there perhaps is no point in keeping it.

**Comment by jidanni** [comment]
Well all I know is something is sounding like the (hated)
https://stackoverflow.com/questions/45729047/disable-the-ctrl-scroll-to-zoom-google-maps .

**Comment by rnorris** [comment]
Select mode is now all powerful and the default.
