### ISSUE TITLE
Allow zero-additional-click properties view when selecting

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#88]
When we select a point often we want to see its properties (expanded
in the Layers panel.) Yes there are several ways to see its properties,
but all involve extra clicking.

Maybe have a second "Properties" panel, to the right of the Layers
panel, that users can keep open or closed. (Default: closed.)
(Currently Properties is a floating panel that needs to opened for each
point.)

**Comment by rnorris** [comment]
Do you specifically mean Trackpoint properties, Waypoint Properties or Layer Properties?

You should be able to leave the Trackpoint property dialog open and select different trackpoints.

However for waypoints it seems the dialog prevents other interaction - which seems like a mistake and should behave like Trackpoint property dialog.

For Layers themselves I don't think there's a lot of use in keeping the dialog available.

**Comment by jidanni** [comment]
> However for waypoints it seems the dialog prevents other interaction - which seems like a mistake and should behave like Trackpoint property dialog.

Yes... that must be it.

**Comment by rnorris** [comment]
The Waypoint dialog preventing other interaction is probably by 'design' - just a simple modal dialog.

Changing it to remain open requires a bit more work than I initially imagined as not only does one need to separate out the applying of the changes from the opening of the dialog, but also sprinkle around some protection about how to handle the Waypoint / layer being deleted whilst this dialog is open (generally similar principals to how the Trackpoint edit is handled).

If would perhaps be unfair that I called it a mistake rather than 'not implemented as fully for better usability'.
