### ISSUE TITLE
Incorrect timezone on Distance-Time and Elevation-Time tabs of Track Properties

### ISSUE THREAD

**Issue by sandaihu** [viking-gps/viking#96]
There's the following scenario as:
- in `Preferences` I have `UTC` set as the `Time Display`
- the GPX file I open saved the timestamps in `UTC` (as GPX generally does)

If I open the track properties, the Start and End times are correctly shown in `UTC`:
![image](https://user-images.githubusercontent.com/17235528/84404880-ae76ef00-ac07-11ea-8272-c93f09cb5cce.png)

Yet if I change to the `Distance-Time` or `Elevation-Time` tabs, the times are displayed in local time (+2 hours):
![image](https://user-images.githubusercontent.com/17235528/84405366-51c80400-ac08-11ea-8f50-b15d81ed85a4.png)

My system-wide timezone is indeed CET/CEST, but shouldn't viking show also these data in UTC, if the Preferences have that set?

Haven't checked yet with v1.8, the above happens with v1.7.

Thanks.

**Comment by rnorris** [comment]
Yes this looks like an oversight; I'm sure this issue is also in v1.8.

IIRC I did have a concern about performance if the time display option was set to 'World' as it might  need to recalculate the timezone for every display update - which might be relatively slow - but the code works out the timezone as used in the Statistics display anyway (i.e. only on initial dialog opening).

Unfortunately it simply appears I forgot to change this bit.

Thanks for noticing and raising this issue.
